In [9]:
import mytools

In [5]:
import pandas as pd
file_path_excel = R'国家认同数据清理后.xlsx'
df_excel = pd.read_excel(file_path_excel)
# 创建民族、年级和政治面貌的交互表
cross_tab = pd.crosstab(index=[df_excel['民族'], df_excel['年级']], 
                        columns=df_excel['政治面貌'], 
                        margins=True,normalize=True)  # All 行和列的总和

cross_tab

政治面貌           1         2         3         4       All
民族  年级
1   0   0.000000  0.000000  0.001284  0.000000  0.001284
    1   0.119384  0.007702  0.010270  0.002567  0.139923
    2   0.116816  0.019255  0.012837  0.002567  0.151476
    3   0.039795  0.028241  0.007702  0.005135  0.080873
    4   0.028241  0.014121  0.002567  0.000000  0.044929
...          ...       ...       ...       ...       ...
36  1   0.001284  0.000000  0.000000  0.000000  0.001284
47  2   0.001284  0.000000  0.000000  0.000000  0.001284
48  1   0.000000  0.001284  0.000000  0.000000  0.001284
97  2   0.001284  0.000000  0.000000  0.000000  0.001284
All     0.736842  0.132221  0.110398  0.020539  1.000000

[78 rows x 5 columns]

In [6]:
df_excel = pd.read_excel(file_path_excel)
# 创建年级、政治面貌和发展信心的交互表
cross_tab = pd.crosstab(index=[df_excel['年级'], df_excel['发展信心']], 
                        columns=df_excel['政治面貌'], 
                        margins=True, normalize=True)  # All 行和列的总和

cross_tab

政治面貌             1         2         3         4       All
年级  发展信心
0   1.0   0.006427  0.000000  0.000000  0.000000  0.006427
    2.0   0.001285  0.000000  0.000000  0.000000  0.001285
    3.0   0.001285  0.000000  0.000000  0.000000  0.001285
    4.0   0.006427  0.000000  0.001285  0.000000  0.007712
1   1.0   0.019280  0.001285  0.002571  0.000000  0.023136
    2.0   0.006427  0.000000  0.000000  0.001285  0.007712
    3.0   0.080977  0.006427  0.012853  0.001285  0.101542
    4.0   0.185090  0.007712  0.017995  0.001285  0.212082
2   1.0   0.011568  0.000000  0.003856  0.000000  0.015424
    2.0   0.010283  0.008997  0.002571  0.000000  0.021851
    3.0   0.086118  0.008997  0.014139  0.001285  0.110540
    4.0   0.137532  0.016710  0.012853  0.005141  0.172237
3   1.0   0.011568  0.005141  0.001285  0.000000  0.017995
    2.0   0.006427  0.000000  0.006427  0.000000  0.012853
    3.0   0.034704  0.016710  0.014139  0.005141  0.070694
    4.0   0.057841  0.034704  0.006427  0.005141  0.104113
4   1.0   0.001285  0.001285  0.002571  0.000000  0.005141
    2.0   0.001285  0.000000  0.000000  0.000000  0.001285
    3.0   0.024422  0.008997  0.006427  0.000000  0.039846
    4.0   0.046272  0.015424  0.005141  0.000000  0.066838
All       0.736504  0.132391  0.110540  0.020566  1.000000